### ISSUE TITLE
После конвертации в description.xml в узле sequence некорректно заполняется  number и id

### ISSUE THREAD

**Issue by ulyantsevsergey** [gribuser/FB3#2]
1. Конвертируем книгу (пробовались книги из серии и не из серии) с помощью importfb3_from_fb2.pl
2. Заходим в fb3/description.xml
   Результат:
   В узел серии всегда выглядит так    <sequence number="1" id="00000000-0000-0000-0000-000000000000">

**Comment by VonShtirlitz** [comment]
это вроде уже поправили
