### ISSUE TITLE
капитель

### ISSUE THREAD

**Issue by ildar** [gribuser/FB3#4]
почему незаслуженно отсутвует капитель https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D0%BF%D0%B8%D1%82%D0%B5%D0%BB%D1%8C_(%D1%88%D1%80%D0%B8%D1%84%D1%82) ?
Это важный элемент в типографике и имеет значение для некоторых типов книг.

**Comment by gribuser** [comment]
Вообще да, непорядок. Надо добавить.

**Comment by gribuser** [comment]
А да, fb3b:smallcaps добавлено ж было (давно)
